name: FriendlyElec R2S
#

env:
  SSH_ACTIONS:  false
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  push:
    paths:
      - 'FriendlyElec-r2s.yml'
  watch:
    types: started
  schedule:
    - cron: '0 12 * * 5'
  release:
    types: [published]
  
jobs:

  build:
    timeout-minutes: 720
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo docker image prune -a -f
          sudo apt-get -y install unzip upx-ucl subversion
          sudo apt-get -y purge dotnet* ghc* google* llvm* mysql* php* zulu* firefox hhvm
          sudo apt-get -y autoremove --purge          
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
          # sudo apt install build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python-distutils-extra python3-setuptools python3-dev quilt rsync subversion swig time xsltproc zlib1g-dev 
          # sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential  bzip2 ccache cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib  git gperf haveged help2man intltool lib32gcc1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply python-docutils qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo apt-get install clang llvm
          sudo apt-get autoclean
          
      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          
      - name: Download Source
        run: |
          rm -rf code
          mkdir code
          cd code
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v22.03   -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
          repo sync -c  --no-clone-bundle
          
      - name: Clone Feeds
        run: |
          cd code/friendlywrt/
          ./scripts/feeds update -a
          
      - name: Install Feeds	
        run: |		
          cd code/friendlywrt		
          ./scripts/feeds install -a
          
      - name: Set Default Values
        run: |
          cd code/friendlywrt
          echo -e "\nBuild date:$(date +%Y-%m-%d), by dongyusen@gmail.com\n" >> package/base-files/files/etc/banner
          
          #rm -f .config*
          #cat ../../feeds-1907.conf > .config
          #cp ../../feeds-1907.conf ../configs/config_rk3328

      - name: SSH连接
        uses: DONGYUSEN/debugger-action@master
        if: env.SSH_ACTIONS == 'true'   
        
      - name: Build OpenWrt
        run: |
          git config --global user.email "dongyusen@gmail.com"
          git config --global user.name "dongyusen"
          
          cd code/
          # sed -i '/feeds/d' scripts/mk-friendlywrt.sh
          # sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          sed -i 's/make -j$(nproc) V=s/make -j8/' scripts/mk-friendlywrt.sh
          # sed -i 's/make -j$(nproc) V=s/make -j1/' scripts/mk-friendlywrt.sh
          ./build.sh nanopi_r2s.mk
         
      - name: Fix Rootfs Owner and Group
        run: |
          sudo df -lh
          #lodev=$(sudo losetup -f)
          #echo "found unused loop dev $lodev"
          #sudo losetup -o 100663296 $lodev code/out/*.img
          ##sudo mkfs -t ext4 $lodev
          #sudo rm -rf /mnt/friendlywrt-tmp
          #sudo mkdir -p /mnt/friendlywrt-tmp
          #sudo mount $lodev /mnt/friendlywrt-tmp
          #sudo chown -R root:root /mnt/friendlywrt-tmp
          #sudo umount /mnt/friendlywrt-tmp
          #sudo losetup -d $lodev
          
      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          #cp code/out/*.img.zip ./artifact/
          zip ./artifact/FriendlyWrt_NanoPi-R2S.img.zip code/out/*.img
          
          ls -lh code/out/*
          cp code/friendlywrt/.config ./artifact/config.seed.txt
          # tar -czvf ./artifact/packages.tar.gz ./code/friendlywrt/bin/targets/rockchip-rk3328/generic/packages/
          
          echo "strDate=$(TZ=UTC-8 date '+%Y-%m-%d')" >> $GITHUB_ENV
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: FriendlyElec-r2s
          path: ./artifact/
          
      - name: set NOW
        run: |
          echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H-%M-%S')"
          
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.8.6
        with:
          name: "FriendlyElec R2s v21.02 官方原版重新编译"
          tag: ${{ env.NOW }}
          #tag_name: ${{env.strDate}} 
          #commit: main
          #replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ./artifact/*.zip,./artifact/*.gz,./artifact/*.txt
          
      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          ##repo: <owner>/<repoName> # defaults to current repo
          keep_latest: 10
          ##delete_tag_pattern: beta # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Delete Artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            FriendlyElec-r2s
