name: NanoPi-R2S OpenWrt 22.03 Build

env:
  SSH_ACTIONS: false
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  

on:
  push:
    #paths:
    #  - 'CHANGELOG.md'
  #watch:
  #  types: started
  schedule:
    - cron: '00 2 * * 5'


jobs:

  build:
    # runs-on: ubuntu-18.04
    runs-on: ubuntu-20.04
    
    steps:
   
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Checkout
        uses: actions/checkout@master
        #with:
        #  ref: master

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d
          wget https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh
          sed -i -e 's/^apt-get -y install openjdk-8-jdk/# apt-get -y install openjdk-8-jdk/g' install.sh
          sed -i -e 's/^\[ -d fa-toolchain \]/# [ -d fa-toolchain ]/g' install.sh
          sed -i -e 's/^(cat fa-toolchain/# (cat fa-toolchain/g' install.sh
          sed -i -e 's/^(tar xf fa-toolchain/# (tar xf fa-toolchain/g' install.sh
          sudo -E bash ./install.sh
          sudo -E update-alternatives --install $(which python) python /usr/bin/python2.7 20

          sudo -E apt-get install clang llvm quilt
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk /usr/local/share/boost /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get autoclean -y
          sudo apt-get autoremove -y
          sudo apt-get autoclean
          
          sudo swapoff -a
                    
          # for git error
          git config --global user.email "dongyusen@gmail.com"
          git config --global user.name "dongyusen"
          
          echo "Free space:"
          df -h
      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
      - name: Download Source
        run: |
          rm -rf code
          mkdir code
          cd code
          cp /usr/bin/repo ./repo
          python2 repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v22.03 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
          python2 repo sync -c  --no-clone-bundle
          
      - name: Update Feeds		
        run: |		
          cd code/friendlywrt
          ./scripts/feeds update -a
          rm -rf feeds/packages/net/zerotier
          
          #rm -rf feeds/packages/lang/golang
          #svn co https://github.com/openwrt/packages/branches/openwrt-22.03/lang/golang feeds/packages/lang/golang
 
      - name: Processing drivers
        run: |
          cd code/friendlywrt/package
          
          #漂亮的主题
          git clone https://github.com/jerrykuku/luci-theme-argon.git custom/luci-theme-argon
          git clone https://github.com/jerrykuku/luci-app-argon-config.git  custom/luci-app-argon-config

          #越过长城
          # disable for test!

          git clone https://github.com/fw876/helloworld.git custom/helloworld
          sed -i 's/ +libopenssl-legacy//g' custom/helloworld/shadowsocksr-libev/Makefile

          # compiler error! so disable it.
          rm  -rf custom/helloworld/shadowsocks-rust 
          
          #git clone https://github.com/xiaorouji/openwrt-passwall2.git custom/openwrt-passwall2
          git clone https://github.com/leiliang75/luci-app-vssr.git custom/luci-app-vssr
          sed -i 's/..\/..\/luci.mk/$(TOPDIR)\/feeds\/luci\/luci.mk/' custom/luci-app-vssr/Makefile
          git clone https://github.com/jerrykuku/lua-maxminddb.git custom/lua-maxminddb


          
          #git clone https://github.com/pymumu/smartdns custom/smartdns-le    

          #广告过滤
          
          #VPN，虚拟局域网
          git clone https://github.com/coolsnowwolf/luci.git --depth 1 --branch master --single-branch applications/luci-app-n2n
          mv applications/luci-app-n2n/applications/luci-app-n2n custom/
          rm -rf applications/luci-app-n2n
          git clone https://github.com/coolsnowwolf/packages.git --depth 1 --branch master --single-branch net/n2n
          mv net/n2n/net/n2n custom/
          rm -rf net/n2n
          
          #系统工具

          
          # kms服务器
          git clone https://github.com/immortalwrt/packages.git --depth 1 --branch master --single-branch net/vlmcsd
          mv net/vlmcsd/net/vlmcsd custom/
          rm -rf net/vlmcsd

          git clone https://github.com/coolsnowwolf/luci.git --depth 1 --branch master --single-branch applications/luci-app-vlmcsd
          mv applications/luci-app-vlmcsd/applications/luci-app-vlmcsd custom/
          rm -rf applications/luci-app-vlmcsd
          
          ## autoreboot 
          git clone https://github.com/coolsnowwolf/luci.git --depth 1 --branch master --single-branch applications/luci-app-autoreboot
          mv applications/luci-app-autoreboot/applications/luci-app-autoreboot custom/
          rm -rf applications/luci-app-autoreboot
          
          ## luci-app-usb-printer && filetransfer
          git clone https://github.com/coolsnowwolf/luci.git --depth 1 --branch master --single-branch applications/luci-app-usb-printer
          mv applications/luci-app-usb-printer/applications/luci-app-usb-printer custom/
          rm -rf applications/luci-app-usb-printer
          
          git clone https://github.com/coolsnowwolf/luci.git --depth 1 --branch master --single-branch applications/luci-app-filetransfer
          mv applications/luci-app-filetransfer/applications/luci-app-filetransfer custom/
          rm -rf applications/luci-app-filetransfer
          # sed -i 's/..\/..\/luci.mk/$(TOPDIR)\/feeds\/luci\/luci.mk/' custom/luci-app-filetransfer/Makefile
          
          git clone https://github.com/coolsnowwolf/luci.git --depth 1 --branch master --single-branch libs/luci-lib-fs
          mv libs/luci-lib-fs/libs/luci-lib-fs custom/
          rm -rf libs/luci-lib-fs
          
          ## 网络驱动
          git clone https://github.com/immortalwrt/immortalwrt.git test
          cp -r test/package/kernel/r8* custom/
          cp -r test/package/kernel/rtl* custom/

          rm -rf test
          rm -rf custom/r8101
          rm -rf custom/rtl8812au-ct
          


          #关闭一些不必要的软件
          #rm -rf custom/luci-app-ssr-plus
          #rm -rf custom/openwrt-passwall/luci-app-passwall
          #rm -rf custom/luci-app-vssr
          #rm -rf custom/luci-app-open
          #rm -rf custom/luci-app-bypass
          
          
          # UPX 可执行软件压缩
          cd ../
          #sed -i '/patchelf pkgconf/i\tools-y += ucl upx' ./tools/Makefile
          #sed -i '\/autoconf\/compile :=/i\$(curdir)/upx/compile := $(curdir)/ucl/compile' ./tools/Makefile
          #svn co https://github.com/immortalwrt/immortalwrt/branches/master/tools/upx tools/upx
          #svn co https://github.com/immortalwrt/immortalwrt/branches/master/tools/ucl tools/ucl
          
      - name: Update Target.mk
        run: |
          cd code/friendlywrt/include
          sed -i 's/dnsmasq /dnsmasq-full default-settings luci /' target.mk
          
          
      - name: Install Feeds		
        run: |		
          cd code/friendlywrt		
          ./scripts/feeds update -a -f
          ./scripts/feeds install -a -f

          rm -rf feeds/packages/lang/golang
          rm -rf feeds/packages/lang/rust
          git clone https://github.com/coolsnowwolf/packages.git --depth 1 --branch master --single-branch test
          mv test/lang/golang feeds/packages/lang/golang
          mv test/lang/rust feeds/packages/lang/rust
          rm -rf test
          
          rm -rf feeds/packages/libs/openssl
          git clone https://github.com/coolsnowwolf/openwrt.git  --depth 1 --branch master --single-branch test
          mv test/package/libs/openssl  feeds/packages/libs/
          rm -rf test
          
          rm -rf feeds/packages/utils/docker-ce
          rm -rf feeds/luci/applications/luci-app-docker
          rm -rf feeds/luci/applications/luci-app-dockerman
          chmod +x ./target/linux/rockchip/armv8/base-files/etc/board.d/01_leds
          chmod +x ./target/linux/rockchip/armv8/base-files/etc/board.d/02_network
          
      - name: Custom Configure Files
        run: |
          rm -f code/friendlywrt/.config*
          cat feeds-1907.conf > code/friendlywrt/.config

      - name: SSH连接
        uses: DONGYUSEN/debugger-action@master
        if: env.SSH_ACTIONS == 'true'
        
      - name: Install ShellClash
        run: |
          cd code/friendlywrt/package/base-files/files
          mkdir -p etc/shellclash
          cd etc/shellclash
          wget -c https://github.com/juewuy/ShellCrash/blob/dev/install.sh
          chmod +x install.sh 
          mv install.sh Crash_install.sh

      - name: Set Default Values
        run: |
          cd code/friendlywrt
          echo -e "\nBuild date:$(date +%Y-%m-%d), by dongyusen@gmail.com\n" >> package/base-files/files/etc/banner
          sed -i 's/timezone='UTC'/timezone='CST-8'/' package/base-files/files/bin/config_generate

          make defconfig
          # make download -j$(($(nproc)+1))
          make download -j12
      
      - name: Install UPX
        run: |
          wget -q -O - https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz | tar -Jx --strip 1 -f - -C code/friendlywrt/staging_dir/host/bin/
          

      - name: Build OpenWrt
        run: |
          
          echo "Free space:"
          df -h
          #########
          cd code
          sed -i '/feeds/d' scripts/mk-friendlywrt.sh          
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          sed -i 's/make -j$(nproc) V=s/make -j1 V=sc/' scripts/mk-friendlywrt.sh
          # sed -i 's/make -j$(nproc) V=s/make -j8 V=s/' scripts/mk-friendlywrt.sh
          # sed -i 's/ +libopenssl-legacy//g' feeds/helloworld/shadowsocksr-libev/Makefile
          
          #git clone https://github.com/friendlyarm/prebuilts.git -b master --depth 1
          #cd prebuilts/gcc-x64
          #sudo tar xvf toolchain-11.3-aarch64.tar.xz -C /
          

      - name: Build OpenWrt2
        run: |
          cd code 
          ./build.sh nanopi_r2s.mk          
        

      #- name: SSH连接
      #  uses: DONGYUSEN/debugger-action@master
      #  if: env.SSH_ACTIONS == 'true'
        

      - name: Fix Rootfs Owner and Group
        run: |
          
          lodev=$(sudo losetup -f)
          echo "found unused loop dev $lodev"
          
          #sudo fdisk -lu code/out/*.img
          #sudo losetup --show -f -P code/out/*.img
          
          #Device                                                   Start     End Sectors   Size Type
          #code/out/FriendlyWrt_20220125_NanoPi-R2S_arm64_sd.img1   16384   24575    8192     4M unknown
          #code/out/FriendlyWrt_20220125_NanoPi-R2S_arm64_sd.img2   24576   32767    8192     4M unknown
          #code/out/FriendlyWrt_20220125_NanoPi-R2S_arm64_sd.img3   32768   40959    8192     4M unknown
          #code/out/FriendlyWrt_20220125_NanoPi-R2S_arm64_sd.img4   40960   49151    8192     4M unknown
          #code/out/FriendlyWrt_20220125_NanoPi-R2S_arm64_sd.img5   49152   81919   32768    16M unknown
          #code/out/FriendlyWrt_20220125_NanoPi-R2S_arm64_sd.img6   81920  163839   81920    40M unknown
          #code/out/FriendlyWrt_20220125_NanoPi-R2S_arm64_sd.img7  163840  262143   98304    48M unknown
          #code/out/FriendlyWrt_20220125_NanoPi-R2S_arm64_sd.img8  262144 1417215 1155072   564M unknown
          #code/out/FriendlyWrt_20220125_NanoPi-R2S_arm64_sd.img9 1417216 1953090  535875 261.7M unknown
          
          sudo losetup -o 134217728 $lodev code/out/*.img
          
          #sudo mkfs -t ext4 $lodev
          sudo rm -rf /mnt/friendlywrt-tmp
          sudo mkdir -p /mnt/friendlywrt-tmp
          sudo mount $lodev /mnt/friendlywrt-tmp
          
          ls -l /mnt/friendlywrt-tmp
          
          sudo chown -R root:root /mnt/friendlywrt-tmp
          
          sudo df -lh
          
          # Copy Some Scripts
          sudo cp ./scripts/cpuinfo.sh /mnt/friendlywrt-tmp/bin/cpuinfo && sudo chmod +x /mnt/friendlywrt-tmp/bin/cpuinfo
          sudo cp ./scripts/ipv6-helper.sh /mnt/friendlywrt-tmp/bin/ipv6-helper.sh && sudo chmod +x /mnt/friendlywrt-tmp/bin/ipv6-helper.sh
          
          # for helloworld subscribe error:
          sudo cp /mnt/friendlywrt-tmp/usr/libexec/wget-ssl /mnt/friendlywrt-tmp/usr/bin/wget-ssl          
          ###
          
          #sudo cp ./scripts/FCN_V3.9_Linux.zip /mnt/friendlywrt-tmp/root
          #sudo cp ./scripts/luci-app-dnsfilter_1.0-8_all.ipk /mnt/friendlywrt-tmp/root
          
          sudo umount /mnt/friendlywrt-tmp
          sudo losetup -d $lodev
          
      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          
          #cd code/out
          #tar -czvf ../../artifact/FriendlyWrt_NanoPi-R2S.img.tar.gz *.img
          
          #cd ../../
          cp code/friendlywrt/.config ./artifact/config.txt
          mv code/out/*.gz ./artifact/
          # cp code/out/FriendlyWrt_NanoPi-R2S.img.tar.gz ./artifact/
          # ls -l code/friendlywrt/bin/targets/rockchip/armv8/*.img*
          mv code/friendlywrt/bin/targets/rockchip/armv8/*.img.gz ./artifact/ 
          md5sum ./artifact/*.gz > ./artifact/md5.txt
          

          # 只保留tar.gz
          # cp code/out/*.zip ./artifact/

          
          
          find ./ -name *.ipk > ./artifact/ipkfiles.txt
          
          ## keep the *.ipk files:
          #mkdir ./artifact/package
          #cp ./code/friendlywrt/bin/packages/aarch64_generic/packages/*.ipk  ./artifact/package
          #cp ./code/friendlywrt/bin/packages/aarch64_generic/luci/*.ipk  ./artifact/package
          #cp ./code/friendlywrt/bin/packages/aarch64_generic/base/*.ipk  ./artifact/package
          #cp ./code/friendlywrt/bin/packages/aarch64_generic/routing/*.ipk  ./artifact/package
          #tar -czvf packages.tar.gz ./artifact/package/*.ipk
          #rm -rf ./artifact/package/
          #mv packages.tar.gz ./artifact/
          #md5sum ./artifact/packages.tar.gz >> ./artifact/md5.txt
          
          echo "strDate=$(TZ=UTC-8 date '+%Y-%m-%d')" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FriendlyWrt_NanoPi-R2S RK3328 v22.03
          path: ./artifact/
 
      - name: set NOW
        run: |
          echo "::set-env name=NOW::$(date +'%Y-%m-%d-%H-%M-%S')"
    
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.8.6
        with:
          name: "Friendlywrt R2s v22.03"
          #allowUpdates: true
          tag: ${{ env.NOW }}
          #tag_name: ${{env.strDate}} 
          #commit: main
          #replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ./artifact/*.gz,./artifact/*.txt
          
      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 15
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
          
      - name: Delete Artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            FriendlyWrt_NanoPi-R2S RK3328 v22.03
