name: NanoPi-R2S RK3328 OpenWrt 19.07 Build

env:
  SSH_ACTIONS:  true
  
on:
  push:
    #paths:
    #  - 'CHANGELOG.md'
  watch:
    types: started
  schedule:
    - cron: '00 18 * * *'

jobs:

  build:
    timeout-minutes: 720
    runs-on: ubuntu-18.04

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          curl https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/852acb5b6511d31a450fd0a8829a0f795b3f21fd/install.sh  | sed '/#/d' | sed 's/\\//g' | sed 's/exit 0//g' | sed 's/sudo apt -y install//g' | sed 's/sudo apt-get -y install//g' | sed 's/:i386//g' | xargs sudo apt-get -y --no-install-recommends install
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk /usr/local/share/boost /opt/ghc

      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/

      - name: Download Source
        run: |
          rm -rf code
          mkdir code
          cd code
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.5 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          cp ../rk3328.xml ../code/.repo/manifests/rk3328.xml
          repo sync -c --no-clone-bundle -j8
          #chmod +x ./target/linux/rockchip-rk3328/base-files/etc/board.d/01_leds
          #chmod +x ./target/linux/rockchip-rk3328/base-files/etc/board.d/02_network
          
      - name: Update Feeds		
        run: |		
          cd code/friendlywrt
          
          # echo 'src-git packages https://github.com/coolsnowwolf/packages;openwrt-19.07' >  feeds.conf.default
          # echo 'src-git luci https://github.com/coolsnowwolf/luci' >>  feeds.conf.default
          # echo 'src-git routing https://git.openwrt.org/feed/routing.git;openwrt-19.07' >>  feeds.conf.default
          # echo 'src-git helloworld https://github.com/fw876/helloworld' >>  feeds.conf.default

          ./scripts/feeds update -a
          
          rm -rf feeds/packages/net/shadowsocks-libev
          rm -rf feeds/packages/net/zerotier

             
      - name: Processing drivers
        run: |
          cd code/friendlywrt/package
          
          #漂亮的主题
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git custom/luci-theme-argon
          
          #越过长城
          git clone https://github.com/xiaorouji/openwrt-passwall.git custom/openwrt-passwall
          mv custom/openwrt-passwall/v2ray-core custom/
          mv custom/openwrt-passwall/v2ray-plugin custom/
          mv custom/openwrt-passwall/xray-core custom/
          mv custom/openwrt-passwall/xray-plugin custom/
          
          #### patch！
          #rm -rf custom/v2ray-core
          #rm -rf custom/v2ray-plugin        
          #cd custom/
          #mkdir v2ray && cd v2ray && wget https://github.com/coolsnowwolf/lede/raw/622af09a79af119f4f719a50988b5b314f723383/package/lean/v2ray/Makefile && sed -i 's/4\.34\.0/4\.37\.2/g' Makefile && sed -i 's/b250f569cb0369f394f63184e748f1df0c90500feb8a1bf2276257c4c8b81bee/ece74b2f0e04d9cd487d1b4d79010f0269b6ee0742aaeb147979e5b97639ffa3/g' Makefile && cd ..
          #mkdir v2ray-plugin && cd v2ray-plugin && wget https://github.com/coolsnowwolf/lede/raw/763081f891c89f86fa6de0defdbfe359fb3aec92/package/lean/v2ray-plugin/Makefile && cd ..
          #sed -i 's/GO111MODULE=on/GO111MODULE=off/' xray-core/Makefile
          #sed -i 's/GO111MODULE=on/GO111MODULE=off/' xray-plugin/Makefile
          #sed -i 's/GO111MODULE=on/GO111MODULE=off/' v2ray/Makefile
          #sed -i 's/GO111MODULE=on/GO111MODULE=off/' v2ray-plugin/Makefile        
          #cd ../
          
          # fix golang && dockce &&
          cd ../
          rm -rf feeds/packages/libs/libcap/ && svn co https://github.com/openwrt/openwrt/trunk/package/libs/libcap feeds/packages/libs/libcap
          rm -rf feeds/packages/lang/golang/ && svn co https://github.com/coolsnowwolf/packages/trunk/lang/golang feeds/packages/lang/golang
          sed -i '/enable-jsonc/i\\t--disable-cloud \\' feeds/packages/admin/netdata/Makefile
          
          svn co https://github.com/lisaac/luci-app-dockerman/trunk/applications/luci-app-dockerman custom/luci-app-dockerman
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-lib-docker  custom/luci-lib-docker

          rm -rf feeds/packages/utils/containerd && svn export https://github.com/coolsnowwolf/packages/trunk/utils/containerd feeds/packages/utils/containerd
          rm -rf feeds/packages/utils/docker-ce && svn export https://github.com/coolsnowwolf/packages/trunk/utils/docker-ce feeds/packages/utils/docker-ce
          rm -rf feeds/packages/utils/libnetwork && svn export https://github.com/coolsnowwolf/packages/trunk/utils/libnetwork feeds/packages/utils/libnetwork
          rm -rf feeds/packages/utils/runc && svn export https://github.com/coolsnowwolf/packages/trunk/utils/runc feeds/packages/utils/runc
          cd package/

          
          
          #####
          
          git clone https://github.com/jerrykuku/lua-maxminddb.git custom/lua-maxminddb
          git clone https://github.com/jerrykuku/luci-app-vssr.git custom/luci-app-vssr
          
          #广告过滤
          git clone https://github.com/rufengsuixing/luci-app-adguardhome.git custom/luci-app-adguardhome
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/adbyby custom/adbyby
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-adbyby-plus custom/luci-app-adbyby-plus
          
          #VPN，虚拟局域网
          ### zerotier
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-zerotier custom/luci-app-zerotier
          svn co https://github.com/coolsnowwolf/packages/trunk/net/zerotier custom/zerotier
          
          #花生壳内网穿透--源代码内容不全，不支持arm64，需要补充！！！！
          #svn co https://github.com/teasiu/dragino2/trunk/devices/common/diy/package/teasiu/luci-app-phtunnel custom/luci-app-phtunnel
          #svn co https://github.com/teasiu/dragino2/trunk/devices/common/diy/package/teasiu/phtunnel custom/phtunnel
          #svn co https://github.com/QiuSimons/dragino2-teasiu/trunk/package/teasiu/luci-app-oray custom/luci-app-oray
          
          #系统工具
          svn co https://github.com/songchenwen/nanopi-r2s/trunk/luci-app-r2sflasher custom/luci-app-r2sflasher
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-netdata custom/luci-app-netdata
          
          #smart dns
          svn co https://github.com/pymumu/smartdns/trunk/package/openwrt custom/smartdns
          svn co https://github.com/pymumu/luci-app-smartdns/branches/lede custom/luci-app-smartdns
          
          # kms服务器
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/vlmcsd  custom/vlmcsd
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-vlmcsd custom/luci-app-vlmcsd
          
          ## autoreboot
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-autoreboot custom/luci-app-autoreboot
          
          ## luci-app-usb-printer
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-usb-printer custom/luci-app-usb-printer
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-filetransfer custom/luci-app-filetransfer
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-lib-fs custom/luci-lib-fs
          
          ## 网络驱动
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/r8125 custom/r8125
          #svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/r8152 custom/r8152
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/r8168 custom/r8168
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8812au-ac custom/rtl8812au-ac 
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8821cu custom/rtl8821cu
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8188eu custom/rtl8188eu
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8192du custom/rtl8192du
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl88x2bu custom/rtl88x2bu
          
          #necessary lib
          #rm -rf feeds/packages/libs/libcap && svn co https://github.com/openwrt/openwrt/trunk/package/libs/libcap feeds/packages/libs/libcap
          
          # UPX 可执行软件压缩
          cd ../
          sed -i '/patchelf pkgconf/i\tools-y += ucl upx' ./tools/Makefile
          sed -i '\/autoconf\/compile :=/i\$(curdir)/upx/compile := $(curdir)/ucl/compile' ./tools/Makefile
          svn co https://github.com/immortalwrt/immortalwrt/branches/master/tools/upx tools/upx
          svn co https://github.com/immortalwrt/immortalwrt/branches/master/tools/ucl tools/ucl

      - name: Update Target.mk
        run: |
          cd code/friendlywrt/include
          sed -i 's/dnsmasq /dnsmasq-full default-settings luci /' target.mk
          
          
      - name: Install Feeds		
        run: |		
          cd code/friendlywrt		
          ./scripts/feeds install -a

      - name: Custom Configure Files
        run: |
          rm -f code/friendlywrt/.config*
          cat feeds-1907.conf > code/friendlywrt/.config
          cp feeds-1907.conf code/configs/config_rk3328
        
      - name: Set Default Values
        run: |
          cd code/friendlywrt
          echo -e "\nBuild date:$(date +%Y-%m-%d), by dongyusen@gmail.com\n" >> package/base-files/files/etc/banner
          make defconfig
          
      - name: Install UPX
        run: |
          wget -q -O - https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz | tar -Jx --strip 1 -f - -C code/friendlywrt/staging_dir/host/bin/

      - name: SSH连接
        uses: DONGYUSEN/debugger-action@master
        if: env.SSH_ACTIONS == 'true'

      - name: Build OpenWrt
        run: |
          cd code
          
          ## manully compiler
          #cd friendlywrt   
          #make defconfig
          #make download -j8
          #make -j$(($(nproc) + 1)) || make -j$(($(nproc) + 1))  V=s
          #time make V=s VERBOSE=1 -j$(nproc) JOBS=$(nproc) 2>&1 | tee build.log | egrep -i '(warn|error)'
          
          #
          sed -i '/feeds/d' scripts/mk-friendlywrt.sh          
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          sed -i 's/make -j$(nproc) V=s/make -j3/' scripts/mk-friendlywrt.sh
          ./build.sh nanopi_r2s.mk
          

      - name: Fix Rootfs Owner and Group
        run: |
          sudo df -lh
          lodev=$(sudo losetup -f)
          echo "found unused loop dev $lodev"
          sudo losetup -o 100663296 $lodev code/out/*.img
          #sudo mkfs -t ext4 $lodev
          sudo rm -rf /mnt/friendlywrt-tmp
          sudo mkdir -p /mnt/friendlywrt-tmp
          sudo mount $lodev /mnt/friendlywrt-tmp
          sudo chown -R root:root /mnt/friendlywrt-tmp
          sudo umount /mnt/friendlywrt-tmp
          sudo losetup -d $lodev

      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cp code/out/*.* ./artifact/
          cp code/friendlywrt/.config ./artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FriendlyWrt_NanoPi-R2S RK3328 v19.07 make build.sh
          path: ./artifact/
