name: purge-r2s test
#

env:
  SSH_ACTIONS:  false
  
on:
  push:
    paths:
      - 'purge-r2s.yml'
  watch:
    types: started

jobs:

  build:
    timeout-minutes: 720
    runs-on: ubuntu-18.04

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo docker image prune -a -f
          sudo apt-get -y install unzip upx-ucl subversion
          sudo apt-get -y purge dotnet* ghc* google* llvm* mysql* php* zulu* firefox hhvm
          sudo apt-get -y autoremove --purge          
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
  
      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          
      - name: Download Source
        run: |
          rm -rf code
          mkdir code
          cd code
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.5 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          cp ../rk3328.xml ../code/.repo/manifests/rk3328.xml
          repo sync -c --no-clone-bundle -j8
          
      - name: Processing drivers
        run: |
          cd code/friendlywrt/package
          
          #漂亮的主题
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git
          
          #越过长城
          git clone https://github.com/xiaorouji/openwrt-passwall.git custom/openwrt-passwall
          svn co https://github.com/vernesong/OpenClash/trunk/luci-app-openclash custom/luci-app-openclash
          git clone https://github.com/jerrykuku/lua-maxminddb.git custom/lua-maxminddb
          git clone https://github.com/jerrykuku/luci-app-vssr.git custom/luci-app-vssr
          
          svn co https://github.com/fw876/helloworld/trunk/luci-app-ssr-plus custom/luci-app-ssr-plus
          svn co https://github.com/fw876/helloworld/trunk/v2ray-core custom/openwrt-passwall/v2ray-core
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/redsocks2 custom/openwrt-passwall/redsocks2
          
          ##### 长城的修改！
          sed -i '/upx/d'  custom/openwrt-passwall/v2ray-plugin/Makefile
          sed -i '/upx/d'  custom/openwrt-passwall/v2ray-core/Makefile
          sed -i '/upx/d'  custom/openwrt-passwall/xray-core/Makefile
          sed -i '/upx/d'  custom/openwrt-passwall/xray-plugin/Makefile
          sed -i '/upx/d'  custom/openwrt-passwall/trojan-go/Makefile
          sed -i 's/export GO111MODULE=on/export GO111MODULE=off/' custom/openwrt-passwall/xray-core/Makefile
          # sed -i 's/export GO111MODULE=on/export GO111MODULE=off/' custom/openwrt-passwall/v2ray-core/Makefile
          # sed -i 's/export GO111MODULE=on/export GO111MODULE=off/' custom/openwrt-passwall/v2ray-plugin/Makefile
          sed -i 's/export GO111MODULE=on/export GO111MODULE=off/' custom/openwrt-passwall/xray-plugin/Makefile
          
          # more custom/openwrt-passwall/xray-core/Makefile
          
          
          #翻越的补丁/或者最新版 -- golang
          # rm -rf feeds/packages/lang/luasec && svn co https://github.com/coolsnowwolf/packages/trunk/lang/luasec feeds/packages/lang/luasec
          # rm -rf feeds/packages/lang/golang/ && svn co https://github.com/coolsnowwolf/packages/trunk/lang/golang feeds/packages/lang/golang
          rm -rf feeds/packages/lang/golang/ && svn co https://github.com/openwrt/packages/trunk/lang/golang feeds/packages/lang/golang
          
          # 广告过滤
          git clone https://github.com/rufengsuixing/luci-app-adguardhome.git custom/luci-app-adguardhome
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/adbyby custom/adbyby
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-adbyby-plus custom/luci-app-adbyby-plus
          
          # VPN，虚拟局域网
          ### zerotier
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-zerotier custom/luci-app-zerotier
          svn co https://github.com/coolsnowwolf/packages/trunk/net/zerotier custom/zerotier
          ### 花生壳内网穿透？无法使用
          #svn co https://github.com/teasiu/dragino2/trunk/devices/common/diy/package/teasiu/luci-app-phtunnel custom/luci-app-phtunnel
          #svn co https://github.com/teasiu/dragino2/trunk/devices/common/diy/package/teasiu/phtunnel custom/phtunnel
          #svn co https://github.com/QiuSimons/dragino2-teasiu/trunk/package/teasiu/luci-app-oray custom/luci-app-oray
          #################http://www.domyself.me/assets/upload/20150612/luci-app-oray.ipk 
          
          # 系统工具
          svn co https://github.com/songchenwen/nanopi-r2s/trunk/luci-app-r2sflasher custom/luci-app-r2sflasher
          ### luci-app-netdata
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-netdata custom/luci-app-netdata
          
          ### luci-app-filebrowser
          svn co https://github.com/immortalwrt/luci/branches/openwrt-21.02/applications/luci-app-filebrowser custom/luci-app-filebrowser
          svn co https://github.com/immortalwrt/packages/branches/openwrt-21.02/utils/filebrowser custom/filebrowser
          
          ### kms服务器
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/vlmcsd  custom/vlmcsd
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-vlmcsd custom/luci-app-vlmcsd
          
          ## autoreboot
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-autoreboot custom/luci-app-autoreboot
          
          ## luci-app-usb-printer
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-usb-printer custom/luci-app-usb-printer
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-filetransfer custom/luci-app-filetransfer
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-lib-fs custom/luci-lib-fs
          
          
          ## 网络驱动
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/r8125 custom/r8125
          # svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/r8152 custom/r8152
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/r8168 custom/r8168
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8812au-ac custom/rtl8812au-ac 
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8821cu custom/rtl8821cu
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8188eu custom/rtl8188eu
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8192du custom/rtl8192du
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl88x2bu custom/rtl88x2bu
  

      - name: Update Target.mk
        run: |
          cd code/friendlywrt/include
          sed -i 's/dnsmasq /dnsmasq-full default-settings luci /' target.mk
         
      - name: Update Feeds		
        run: |		
          cd code/friendlywrt		
          ./scripts/feeds update -a		
          ./scripts/feeds install -a

      - name: Set Default Values
        run: |
          cd code/friendlywrt
          echo -e "\nBuild date:$(date +%Y-%m-%d), by dongyusen@gmail.com\n" >> package/base-files/files/etc/banner

      - name: Install UPX
        run: |
          wget -q -O - https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz | tar -Jx --strip 1 -f - -C code/friendlywrt/staging_dir/host/bin/
          #cat feeds-1907.conf > code/friendlywrt/.config
          #cd code/friendlywrt
          #make defconfig

      - name: SSH连接
        uses: DONGYUSEN/debugger-action@master
        if: env.SSH_ACTIONS == 'true'   
        
      - name: Build OpenWrt
        run: |
          
          cat feeds-1907.conf > code/friendlywrt/.confi
          
          ######################### mannully
          # cd code/friendlywrt
          #make download -j4
          #make -j$(($(nproc) + 1)) 
          # || make -j1 V=s  
          
          ######################### 
          cd code/
          sed -i '/feeds/d' scripts/mk-friendlywrt.sh
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          sed -i 's/make -j$(nproc) V=s/make -j3/' scripts/mk-friendlywrt.sh
          ./build.sh nanopi_r2s.mk
         
      - name: Fix Rootfs Owner and Group
        run: |
          sudo df -lh
          lodev=$(sudo losetup -f)
          echo "found unused loop dev $lodev"
          sudo losetup -o 100663296 $lodev code/out/*.img
          #sudo mkfs -t ext4 $lodev
          sudo rm -rf /mnt/friendlywrt-tmp
          sudo mkdir -p /mnt/friendlywrt-tmp
          sudo mount $lodev /mnt/friendlywrt-tmp
          sudo chown -R root:root /mnt/friendlywrt-tmp
          sudo umount /mnt/friendlywrt-tmp
          sudo losetup -d $lodev
          
      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cp code/out/*.img.zip ./artifact/
          
          ls -lh code/out/*
          cp code/friendlywrt/.config ./artifact/config.seed.txt
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: purge-r2s
          path: ./artifact/
