name: purge-r2s test
#

env:
  SSH_ACTIONS:  false
  
on:
  push:
    paths:
      - 'purge-r2s.yml'
  watch:
    types: started

jobs:

  build:
    timeout-minutes: 720
    runs-on: ubuntu-18.04

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo docker image prune -a -f
          sudo apt-get -y install unzip upx-ucl subversion
          sudo apt-get -y purge dotnet* ghc* google* llvm* mysql* php* zulu* firefox hhvm
          sudo apt-get -y autoremove --purge          
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
  
      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          
      - name: Download Source
        run: |
          rm -rf code
          mkdir code
          cd code
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.5 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          cp ../rk3328.xml ../code/.repo/manifests/rk3328.xml
          repo sync -c --no-clone-bundle -j8
          
      - name: Processing drivers
        run: |
          cd code/friendlywrt/package
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git
          svn co https://github.com/songchenwen/nanopi-r2s/trunk/luci-app-r2sflasher custom/luci-app-r2sflasher
          git clone https://github.com/xiaorouji/openwrt-passwall.git custom/openwrt-passwall
          svn co https://github.com/vernesong/OpenClash/trunk/luci-app-openclash custom/luci-app-openclash
          git clone https://github.com/rufengsuixing/luci-app-adguardhome.git custom/luci-app-adguardhome
          
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/r8125 custom/r8125
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/r8152 custom/r8152
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/r8168 custom/r8168
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8812au-ac custom/rtl8812au-ac 
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8821cu custom/rtl8821cu
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8188eu custom/rtl8188eu
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8192du custom/rtl8192du
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl88x2bu custom/rtl88x2bu
  
          # 花生壳内网穿透
          #svn co https://github.com/teasiu/dragino2/trunk/devices/common/diy/package/teasiu/luci-app-phtunnel custom/luci-app-phtunnel
          #svn co https://github.com/teasiu/dragino2/trunk/devices/common/diy/package/teasiu/phtunnel custom/phtunnel
          #svn co https://github.com/QiuSimons/dragino2-teasiu/trunk/package/teasiu/luci-app-oray custom/luci-app-oray
          #http://www.domyself.me/assets/upload/20150612/luci-app-oray.ipk 

          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/adbyby custom/adbyby
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-adbyby-plus custom/luci-app-adbyby-plus
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-zerotier custom/luci-app-zerotier
          svn co https://github.com/coolsnowwolf/packages/trunk/net/zerotier custom/zerotier
          
          # luci-app-netdata
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-netdata custom/luci-app-netdata
          git clone https://github.com/jerrykuku/lua-maxminddb.git custom/lua-maxminddb
          git clone https://github.com/jerrykuku/luci-app-vssr.git custom/luci-app-vssr
          #svn co https://github.com/fw876/helloworld/trunk/luci-app-ssr-plus custom/luci-app-ssr-plus
       
      - name: Update Target.mk
        run: |
          cd code/friendlywrt/include
          sed -i 's/dnsmasq /dnsmasq-full default-settings luci /' target.mk          
          
      - name: Update Feeds		
        run: |		
          cd code/friendlywrt		
          ./scripts/feeds update -a		
          ./scripts/feeds install -a
          

        

      - name: Set Default Values
        run: |
          cd code/friendlywrt
          echo -e "\nBuild date:$(date +%Y-%m-%d), by dongyusen@gmail.com\n" >> package/base-files/files/etc/banner
                


      - name: Install UPX
        run: |
          wget -q -O - https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz | tar -Jx --strip 1 -f - -C code/friendlywrt/staging_dir/host/bin/
          #cat feeds-1907.conf > code/friendlywrt/.config
          #cd code/friendlywrt
          #make defconfig

      - name: SSH连接
        uses: DONGYUSEN/debugger-action@master
        if: env.SSH_ACTIONS == 'true'   
        
      - name: Build OpenWrt
        run: |
          # cat r2s-rk3328-config > code/friendlywrt/.config
          # cat feeds-1907.conf > code/friendlywrt/.config
          
          #cd code
          #sed -i '/feeds/d' scripts/mk-friendlywrt.sh
          #sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          #sed -i 's/make -j$(nproc) V=s/make -j3/' scripts/mk-friendlywrt.sh
          #./build.sh nanopi_r2s.mk
          
          #########################
          cd code/friendlywrt
          make defconfig
          
          echo 'CONFIG_PACKAGE_luci-app-ssr-plus=y' >> .config
          echo 'CONFIG_PACKAGE_luci-app-openclash=y' >> .config
          echo 'CONFIG_PACKAGE_luci-app-passwall=y' >> .config
          
          echo 'CONFIG_PACKAGE_luci-theme-argon=y' >> .config
          
          echo 'CONFIG_PACKAGE_luci-app-adguardhome=y' >> .config
          
          echo 'CONFIG_PACKAGE_adbyby=y' >> .config
          echo 'CONFIG_PACKAGE_luci-app-adbyby-plus=y' >> .config
          
          echo 'CONFIG_PACKAGE_luci-app-vlmcsd=y' >> .config
          echo 'CONFIG_PACKAGE_luci-app-zerotier=y' >> .config
          echo 'CONFIG_PACKAGE_luci-app-netdata=y' >> .config
          
          echo 'CONFIG_PACKAGE_luci-app-autoreboot=y' >> .config
          echo 'CONFIG_PACKAGE_luci-app-filebrowser=y' >> .config
          
          echo 'CONFIG_PACKAGE_kmod-r8125=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-r8152=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-r8168=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-rtl8812au-ac=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-rtl8821cu=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-rtl8188eu=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-rtl8192du=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-rtl88x2bu=y' >> .config
          
          make download -j2
          make -j$(($(nproc) + 1)) || make -j1 V=s  
          
      - name: Fix Rootfs Owner and Group
        run: |
          sudo df -lh
          lodev=$(sudo losetup -f)
          echo "found unused loop dev $lodev"
          sudo losetup -o 100663296 $lodev code/out/*.img
          #sudo mkfs -t ext4 $lodev
          sudo rm -rf /mnt/friendlywrt-tmp
          sudo mkdir -p /mnt/friendlywrt-tmp
          sudo mount $lodev /mnt/friendlywrt-tmp
          sudo chown -R root:root /mnt/friendlywrt-tmp
          sudo umount /mnt/friendlywrt-tmp
          sudo losetup -d $lodev
          
      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cp code/out/*.img.zip ./artifact/
          ls -lh code.out/*
          cp code/friendlywrt/.config ./artifact/config.seed.txt
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: purge-r2s
          path: ./artifact/
