name: NanoPi-R2S test

env:
  SSH_ACTIONS:  false
  
on:
  push:
    paths:
      - 'CHANGELOG.md'
  watch:
    types: started

jobs:

  build:
    timeout-minutes: 720
    runs-on: ubuntu-18.04

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo docker image prune -a -f
          sudo apt-get -y install unzip upx-ucl subversion
          sudo apt-get -y purge dotnet* ghc* google* llvm* mysql* php* zulu* firefox hhvm
          sudo apt-get -y autoremove --purge          
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
      #- name: Setup Debug Session
      #  uses: P3TERX/debugger-action@master
  
      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
      - name: Download Source
        run: |
          rm -rf code
          mkdir code
          cd code
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.5 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          cp ../rk3328.xml ../code/.repo/manifests/rk3328.xml
          repo sync -c --no-clone-bundle -j8
      - name: Merge LEDE
        run: |
          cd code
          #git clone https://github.com/coolsnowwolf/lede
          
          cd friendlywrt
          
          #cp -r ../lede/package/lean package/
          #cp -r ../lede/package/libs/pcre package/libs/
          
          echo 'src-git routing https://git.openwrt.org/feed/routing.git' > feeds.conf.default
          echo 'src-git telephony https://git.openwrt.org/feed/telephony.git' >> feeds.conf.default
          echo 'src-git freifunk https://github.com/freifunk/openwrt-packages.git' >> feeds.conf.default
          echo 'src-git packages https://github.com/friendlyarm/friendlywrt_project_packages' >> feeds.conf.default
          echo 'src-git luci https://github.com/friendlyarm/friendlywrt_project_luci' >> feeds.conf.default
          
      - name: Processing drivers
        run: |

          cd code/friendlywrt/package
   
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8812au-ac custom/rtl8812au-ac 
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8821cu custom/rtl8821cu
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8188eu custom/rtl8188eu
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl8192du custom/rtl8192du
          svn co https://github.com/immortalwrt/immortalwrt/trunk/package/kernel/rtl88x2bu custom/rtl88x2bu
  
          # 花生壳内网穿透
          #svn co https://github.com/teasiu/dragino2/trunk/devices/common/diy/package/teasiu/luci-app-phtunnel custom/luci-app-phtunnel
          #svn co https://github.com/teasiu/dragino2/trunk/devices/common/diy/package/teasiu/phtunnel custom/phtunnel
          #svn co https://github.com/QiuSimons/dragino2-teasiu/trunk/package/teasiu/luci-app-oray custom/luci-app-oray
          
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/adbyby custom/adbyby
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-adbyby-plus custom/luci-app-adbyby-plus

          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/vlmcsd  custom/vlmcsd
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-vlmcsd custom/luci-app-vlmcsd
          
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-zerotier custom/luci-app-zerotier
          svn co https://github.com/coolsnowwolf/packages/trunk/net/zerotier custom/zerotier
          
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/luci-app-autoreboot custom/luci-app-autoreboot
          
          svn co https://github.com/immortalwrt/luci/branches/openwrt-21.02/applications/luci-app-filebrowser custom/luci-app-filebrowser
          svn co https://github.com/immortalwrt/packages/branches/openwrt-21.02/utils/filebrowser custom/filebrowser
          
          # git clone https://github.com/xiaorouji/openwrt-passwall.git custom/openwrt-passwall
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/luci-app-passwall
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/tcping
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/ssocks
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/trojan-plus
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/trojan-go
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/naiveproxy
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/brook
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/chinadns-ng
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/xray-core
          svn co https://github.com/xiaorouji/openwrt-passwall/trunk/xray-plugin
          sed -i '/upx/d' trojan-go/Makefile
          
          svn co https://github.com/songchenwen/nanopi-r2s/trunk/luci-app-r2sflasher
          svn co https://github.com/pymumu/smartdns/trunk/package/openwrt smartdns
          svn co https://github.com/pymumu/luci-app-smartdns/branches/lede luci-app-smartdns
          svn co https://github.com/lisaac/luci-app-dockerman/trunk/applications/luci-app-dockerman          
          
          # fix golang
          rm -rf feeds/packages/lang/luasec && svn co https://github.com/coolsnowwolf/packages/trunk/lang/luasec feeds/packages/lang/luasec
          rm -rf feeds/packages/lang/golang/ && svn co https://github.com/coolsnowwolf/packages/trunk/lang/golang feeds/packages/lang/golang
          
          rm -rf feeds/packages/utils/containerd && svn export https://github.com/coolsnowwolf/packages/trunk/utils/containerd feeds/packages/utils/containerd
          rm -rf feeds/packages/utils/docker-ce && svn export https://github.com/coolsnowwolf/packages/trunk/utils/docker-ce feeds/packages/utils/docker-ce
          rm -rf feeds/packages/utils/libnetwork && svn export https://github.com/coolsnowwolf/packages/trunk/utils/libnetwork feeds/packages/utils/libnetwork
          rm -rf feeds/packages/utils/runc && svn export https://github.com/coolsnowwolf/packages/trunk/utils/runc feeds/packages/utils/runc
          sed -i '/STAMP_BUILT/d' feeds/packages/utils/runc/Makefile
          sed -i '/STAMP_BUILT/d' feeds/packages/utils/containerd/Makefile
          
          # fix xtables-addons:
          #rm -rf package/feeds/packages/xtables-addons && svn co https://github.com/Lienol/openwrt-packages/trunk/net/xtables-addons  package/feeds/packages/xtables-addons


      - name: Update Target.mk
        run: |
          cd code/friendlywrt/include
          sed -i 's/dnsmasq /dnsmasq-full default-settings luci /' target.mk
          
          
      - name: Update Feeds		
        run: |		
          cd code/friendlywrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
       
         
      - name: Custom Configure Files
        run: |
          rm -f code/friendlywrt/.config*
          cp feeds-1907.conf code/friendlywrt/config_rk3328
          # cat feeds-1907.conf >  code/friendlywrt/.config
          cat feeds-1907.conf >  code/friendlywrt/.config
          
      - name: Set Default Values
        run: |
          cd code/friendlywrt
          echo -e "\nBuild date:$(date +%Y-%m-%d), by dongyusen@gmail.com\n" >> package/base-files/files/etc/banner
          mkdir -p code/friendlywrt/staging_dir/host/bin
          wget -q -O - https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz | tar -Jx --strip 1 -f - -C code/friendlywrt/staging_dir/host/bin/
      
      - name: SSH连接
        uses: DONGYUSEN/debugger-action@master
        if: env.SSH_ACTIONS == 'true'

      - name: Build OpenWrt
        run: |
          cd code/friendlywrt
          make defconfig
          make download -j2
          make -j$(($(nproc) + 1)) || make -j1 V=s
          # make -j1 
          
      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cp -a code/friendlywrt/bin/targets/*/* artifact

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: FriendlyWrt_NanoPi-R2S test
          path: ./artifact/
